- project:
    check:
      jobs:
        - ansible-test-sanity
        - ansible-role-tests-2.6-py2
        - ansible-role-tests-2.6-py3
    gate:
      jobs:
        # inverted Python version compared to `check`
        - ansible-test-sanity
        - ansible-role-tests-2.6-py2
        - ansible-role-tests-2.6-py3
